// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $("#search-tool").click(function() {
      $(".menu").fadeToggle("fast");
      $(".menu").toggleClass("menu-opened");
      $(".results").fadeToggle("fast");
      $(".results").toggleClass("results-closed");
      return $("#search-tool").toggleClass("toggle-button-selected");
    });
  });

}).call(this);
