// Generated by CoffeeScript 1.7.1
(function() {
  var fade, scrollHeight;

  fade = function(elems, isFadeIn, duration) {
    if (isFadeIn) {
      return elems.fadeIn(duration);
    } else {
      return elems.fadeOut(duration);
    }
  };

  scrollHeight = function() {
    return $(document).height() - $(window).height();
  };

  $(document).ready(function() {
    var body, bottom, duration, isBottomVisible, isFirefox, isTopVisible, top, updateButton;
    top = $("#scroll-to-top");
    bottom = $("#scroll-to-bottom");
    duration = 500;
    isFirefox = typeof InstallTrigger !== "undefined" && InstallTrigger !== null;
    body = $(isFirefox ? "html" : "body");
    isTopVisible = true;
    isBottomVisible = true;
    top.click(function() {
      return body.animate({
        scrollTop: 0
      }, duration);
    });
    bottom.click(function() {
      return body.animate({
        scrollTop: scrollHeight()
      }, duration);
    });
    updateButton = function() {
      duration = "fast";
      if (isTopVisible !== (body.scrollTop() > 0)) {
        fade(top, isTopVisible = !isTopVisible, duration);
      }
      if (isBottomVisible !== (body.scrollTop() < scrollHeight())) {
        return fade(bottom, isBottomVisible = !isBottomVisible, duration);
      }
    };
    $(window).scroll(updateButton);
    return updateButton();
  });

}).call(this);
